In [1]:
import numpy as np

In [2]:
data = np.load('datasets/iris/iris_train_data.npy')

In [3]:
data

array([[5.1, 3.8, 1.6, 0.2],
       [5.6, 2.9, 3.6, 1.3],
       [4.6, 3.4, 1.4, 0.3],
       [5.2, 2.7, 3.9, 1.4],
       [5.5, 2.4, 3.8, 1.1],
       [5.4, 3.9, 1.7, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.4, 3. , 4.5, 1.5],
       [7.3, 2.9, 6.3, 1.8],
       [5.6, 2.7, 4.2, 1.3],
       [5. , 3.3, 1.4, 0.2],
       [6. , 2.2, 4. , 1. ],
       [7.1, 3. , 5.9, 2.1],
       [6.9, 3.2, 5.7, 2.3],
       [6.9, 3.1, 5.1, 2.3],
       [6.4, 2.9, 4.3, 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [4.9, 3.1, 1.5, 0.1],
       [6.2, 2.9, 4.3, 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [5.7, 2.8, 4.1, 1.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.3, 3.3, 6. , 2.5],
       [6. , 3.4, 4.5, 1.6],
       [4.9, 3.1, 1.5, 0.2],
       [7.2, 3.2, 6. , 1.8],
       [4.8, 3.1, 1.6, 0.2],
       [6.1, 3. , 4.9, 1.8],
       [5.1, 3.8, 1.9, 0.4],
       [5.1, 3.3, 1.7, 0.5],
       [5. , 3.4, 1.6, 0.4],
       [6.2, 2.8, 4.8, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.7, 3. , 6.1, 2.3],
       [5.8, 2

In [4]:
labels = np.load('datasets/iris/iris_train_labels.npy')

In [5]:
labels

array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0

In [11]:
mean = np.mean(data, axis=0)
std = np.std(data, axis=0)

In [12]:
(data - mean) / std

array([[-0.93315523,  1.82754542, -1.29699213, -1.38925211],
       [-0.34004809, -0.3558053 , -0.15258731,  0.06154914],
       [-1.52626237,  0.85716732, -1.41143261, -1.25736109],
       [-0.8145338 , -0.84099435,  0.01907341,  0.19344017],
       [-0.45866952, -1.56877793, -0.03814683, -0.2022329 ],
       [-0.57729095,  2.07013995, -1.23977189, -1.12547006],
       [-0.93315523,  1.09976185, -1.41143261, -1.25736109],
       [-0.57729095, -0.11321078,  0.36239486,  0.32533119],
       [ 1.67651618, -0.3558053 ,  1.3923592 ,  0.72100426],
       [-0.34004809, -0.84099435,  0.19073414,  0.06154914],
       [-1.05177666,  0.6145728 , -1.41143261, -1.38925211],
       [ 0.13443762, -2.05396698,  0.07629365, -0.33412393],
       [ 1.43927332, -0.11321078,  1.16347824,  1.11667733],
       [ 1.20203047,  0.37197827,  1.04903775,  1.38045938],
       [ 1.20203047,  0.12938375,  0.70571631,  1.38045938],
       [ 0.60892333, -0.3558053 ,  0.24795438,  0.06154914],
       [ 0.72754476, -0.

In [14]:
train = np.load('datasets/iris/iris_train_data.npy')

In [15]:
train.shape

(105, 4)

In [16]:
valid = np.load('datasets/iris/iris_val_data.npy')

In [17]:
valid.shape

(15, 4)

In [18]:
test = np.load('datasets/iris/iris_test_data.npy')

In [19]:
test.shape

(30, 4)

In [26]:
105+15+30

150

In [28]:
30/150

0.2

In [21]:
indian = np.loadtxt('datasets/pima-indians-diabetes.txt', delimiter=',')

In [22]:
indian.shape

(768, 9)

In [23]:
indian[0]

array([  6.   , 148.   ,  72.   ,  35.   ,   0.   ,  33.6  ,   0.627,
        50.   ,   1.   ])

In [25]:
indian[:,:-1]

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [33]:
round(768*0.2)

154

In [31]:
538+154

692

In [32]:
len(indian)

768

In [34]:
training_labels = np.load('datasets/iris/iris_train_labels.npy')

In [35]:
training_labels.shape

(105, 3)

In [36]:
training_labels

array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0

In [38]:
whole_set = np.loadtxt('datasets/pima-indians-diabetes.txt', delimiter=',')
input_set = whole_set[:,:-1]
label_set = whole_set[:,-1]


In [39]:
label_set.shape

(768,)

In [41]:
label_set[:,np.newaxis]

array([[1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],

In [42]:
training_set = np.load('datasets/iris/iris_train_data.npy')

In [43]:
training_set

array([[5.1, 3.8, 1.6, 0.2],
       [5.6, 2.9, 3.6, 1.3],
       [4.6, 3.4, 1.4, 0.3],
       [5.2, 2.7, 3.9, 1.4],
       [5.5, 2.4, 3.8, 1.1],
       [5.4, 3.9, 1.7, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.4, 3. , 4.5, 1.5],
       [7.3, 2.9, 6.3, 1.8],
       [5.6, 2.7, 4.2, 1.3],
       [5. , 3.3, 1.4, 0.2],
       [6. , 2.2, 4. , 1. ],
       [7.1, 3. , 5.9, 2.1],
       [6.9, 3.2, 5.7, 2.3],
       [6.9, 3.1, 5.1, 2.3],
       [6.4, 2.9, 4.3, 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [4.9, 3.1, 1.5, 0.1],
       [6.2, 2.9, 4.3, 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [5.7, 2.8, 4.1, 1.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.3, 3.3, 6. , 2.5],
       [6. , 3.4, 4.5, 1.6],
       [4.9, 3.1, 1.5, 0.2],
       [7.2, 3.2, 6. , 1.8],
       [4.8, 3.1, 1.6, 0.2],
       [6.1, 3. , 4.9, 1.8],
       [5.1, 3.8, 1.9, 0.4],
       [5.1, 3.3, 1.7, 0.5],
       [5. , 3.4, 1.6, 0.4],
       [6.2, 2.8, 4.8, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.7, 3. , 6.1, 2.3],
       [5.8, 2

In [44]:
input_set = whole_set[:,:-1]

In [45]:
input_set

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [46]:
label_set

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 0.

In [47]:
1-label_set

array([0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 0., 0., 0., 1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 1.,
       1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 1., 0., 1.,
       1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0.,
       1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1.,
       1., 0., 1., 1., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       1., 0., 0., 1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1.,
       0., 0., 1., 1., 1., 0., 1., 0., 1., 0., 1., 1., 1., 1., 1., 0., 0.,
       0., 0., 0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1.,
       1., 1., 0., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 1., 1., 1., 1.

In [50]:
np.concatenate((label_set[:, np.newaxis], 1-label_set[:,np.newaxis]), axis=1)

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       ...,
       [0., 1.],
       [1., 0.],
       [0., 1.]])